wagtail/guide

- .gitignore
- .gitpod.dockerfile
- .gitpod.yml
- README.md
Try it yourself: https://gitpod.io#https://github.com/wagtail/guide/
> Add Gitpod

- apps/core/factories.py
- apps/core/management/commands/buildfixtures.py
- apps/core/models/content.py
- apps/core/templates/base.html
- apps/core/templates/components/navigation.html
- apps/core/templates/core/content_page.html
- apps/core/templatetags/core_tags.py
- apps/core/tests/test_management_commands.py
- apps/frontend/static_src/scss/components/navigation.scss
- apps/frontend/static_src/scss/main.scss
- apps/frontend/static_src/scss/variables.scss
I raised this in our Slack channel. Added it here as archive. 
I tried to create the navigation and am fighting the data structure a bit.
- It is impossible to navigate from 'Tutorials' to 'How-to'. The main navigation is missing.
- The collapsed navigation hide relevant information.
- The collapsed navigation is harder to use. As a user needs to click, click, click to expand the collapsed sections.
In the current guide, the page 'Finding your way around' duplicates the navigation. It is redundant.
https://docs.wagtail.org/en/stable/editor_manual/finding_your_way_around/index.html
If we drop the redundant 'in between pages', we loose a level, we can drop the collapse feature :tada:
Mockup:
1. The current design.
2. Drop the lowest level, the contents of these pages can be on "Finding your …
> Add main nav

- apps/core/templates/core/content_page.html
- apps/core/templatetags/core_tags.py
- apps/frontend/static_src/scss/components/nav_button.scss
- apps/frontend/static_src/scss/main.scss
I have added previous and next buttons for content pages. For that I have registered 2 filters namely `previous_page` and `next_page` which have their own logic for returning their respective pages. I have designed the buttons according to the design on figma. I have also added a new scss file `nav_button.scss` in `apps/frontend/static_src/scss/components/` for styling and adding hover effects on the buttons. The buttons seemed to be working fine when tested locally.
I am attaching the screenshot of the end result:
> add previous and next buttons

- apps/core/wagtail_hooks.py
- apps/frontend/static_src/scss/components/rich-text.scss
Fixes #81 
@thibaudcolas I have added the inline style for keyboard inputs. I am attaching the screenshots of the final result. I have copied the css from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd. Let me know if the css is to be changed.
> Add inline keyboard text style in rich text. Fix #81

- apps/core/tests/test_previous_page_and_next_page.py
* When running `make lint` - a few files were failing so I have fixed them up so that I can test additional linting.
```
$ make lint
poetry run flake8 apps
apps/core/tests/test_previous_page_and_next_page.py:19:9: A502 prefer assertIsNone() instead of comparing to None
apps/core/tests/test_previous_page_and_next_page.py:32:9: A502 prefer assertIsNone() instead of comparing to None
make: *** [Makefile:16: lint] Error 1
```
> Tests - fix up Python linting issues

- apps/core/tests/test_locales.py
- monkey_patches.py
There is a part of Wagtail that calls Django's `get_language_info()` with its own language code (from [here](https://github.com/wagtail/wagtail/blob/f77229da2a0dc93520b9083552d312217382de1a/wagtail/admin/localization.py#L6-L44)) instead of obtaining it from the `LANGUAGES` or `WAGTAIL_CONTENT_LANGUAGES` settings.
Our monkey patch assumes that the `get_language_info()` function is always called with our version-suffixed language codes. So, this fails when a language has a region specifier but the language identifier itself doesn't exist in Django's `LANG_INFO`. For example `zh-hans`, with our assumption would become `zh` after trying to strip the version number, but `zh` doesn't exist. This doesn't happen with `pt-br` and `pt-pt` because the `pt` key exists in `LANG_INFO`.
This PR updates …
> Fix monkey patch for `get_language_info()`

- .github/workflows/test.yml
- README.md
- Fixes #151 - this is the final original todo item of that issue.
- Avoid hard-coding Node version where possible and instead reference the nvmrc file, including the Github action - https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file
- Also moves git to the top of the list of dependencies
- Note: All other items on https://github.com/wagtail/guide/issues/151 will be split to new issues.
> Add `fnm` details to README & reference nvmrc file for Node version

- apps/frontend/static_src/scss/components/alert.scss
- apps/frontend/static_src/scss/components/rich-text-image.scss
> Add shadow to images, prevent bleeding. Fix #166

- apps/frontend/static_src/scss/components/header.scss
Small fix to prevent the left column scrolling 20px before sticking on large viewports
> Prevent left column scrolling 20px before sticking

- .github/workflows/ci.yml
- Makefile
- Fixes #189
- Adds titles to each job
- Split out the Python (Django) tests to their own job
- Split backend/frontend linting to their own isolated jobs
- Allow make format & make lint to be run as frontend/backend only versions also
> Split CI steps

- apps/core/models/content.py
- apps/core/tests/test_content_page.py
Fixes #182.
I spent some time digging into this, looks like wagtail-localize completely skips over custom rich text features we added here:
https://github.com/wagtail/guide/blob/60cb0bb278e1a295b295734acb51d0e0ba7ded00/apps/richtext/wagtail_hooks.py#L7-L41
I haven't found a way to fix this properly, as it seems that it's just how wagtail-localize works, i.e. it separates out the HTML stuff from user-facing strings.
This PR adds a workaround by using the existing id (in the original language) so that links will still work (though the anchor slug will be in the original language, e.g. English).
This issue only happens with synced translations. Unsynced translations work normally.
~~I'll try to add tests tomorrow.~~ Added.
> Use original id when generating links in table of contents

- apps/core/templates/base.html
- apps/core/templates/components/hreflangs.html
- apps/core/templates/components/language_selector.html
- apps/core/templatetags/core_tags.py
- apps/core/tests/test_alternate_link_tag.py
Fixes #194 and #195.
Needs tests.
> Fix html `lang` attribute and generate `hreflang` links to translations

- apps/core/templatetags/core_tags.py
Fixes https://sentry.io/organizations/wagtail-org/issues/3699443518/?project=4504043711037440
Honestly don't know why this happens as Django's `get_language()` function should fall back to `settings.LANGUAGE_CODE`, and I thought we could assume the `HomePage` with the default `LANGUAGE_CODE` (i.e. `en-latest`) exists. Not sure how to test it either as this doesn't seem to happen locally. I'll add another PR if I find a way to test this.
> Fix home page crash when translation cannot be found

- apps/core/templates/core/blocks/alert.html
> Adding a {% trans %} tag to translate Alert headings.

- apps/frontend/static_src/scss/components/language-selector.scss
> Fix dropdown item hover bgcolor in dark mode

- apps/core/middleware.py
- apps/core/templates/components/language_selector.html
Fixes #263 
I think it is pointless to show a button with only the active locale (which might not have any pages at all) and simpler to just remove in those cases. The only case that I know of right now is the 404.html template which is just a dumb template that has no idea of where to direct the user to go.
I added a bit more logic in the homepage selection middleware introduced in #257 so that the english language is activated instead of the incorrectly selected one. That way the user has the site tree to the left to navigate to the english version of the guide.
> Remove language selector when we don't have a page to show versions of.

- apps/core/middleware.py
Fixes #262.
Move the homepage lookup after response handling so that we have access to the url resolver. Then check if the requested path belongs to i18n_patterns so that we are not handling e.g. `/admin` as a localized URL.
To test this you will need to:
1. Make sure the browser language is english
1.  Test that `/admin` works properly
2. Test that  `/` works properly and redirects to `/en-latest``
2. Change browser language to Deutsch
1. Test that `/admin` works properly 
2. Test that `/` redirects to `/de-latest/` and shows a 404 page with the English menu
> Fixes invalid redirection for /admin when browser is not set to English

- apps/core/middleware.py
- apps/core/tests/test_locales.py
If the root URL is opened with an HTTP_ACCEPT_LANGUAGE where no translation is available, a 404 error is returned. 
See issue https://github.com/wagtail/guide/issues/308.
Instead of a 404 error, users are now redirected to the default language.
> redirect to default language instead of a 404 error

- apps/core/templates/components/feedback.html
- apps/core/tests/test_feedback.py
fixes #311 by always setting a CSRF token when the feedback buttons are rendered.
> render csrf token in feedback form

- apps/frontend/static_src/scss/components/alert.scss
Fixes https://github.com/wagtail/guide/issues/281
> Set height for alert icon

- apps/core/templates/base.html
- apps/search/views.py
This prevents malicious index results from being created, and ensures Google doesn't waste its time on crawling the page.
See also https://github.com/wagtail/wagtail.org/pull/414
> Don't index search results

- apps/core/models/content.py
- apps/search/views.py
Fixes #371,  #278 and #290. Target the Wagtail 5.0 upgrades branch to use `autocomplete`.
> Full text search and partial matches in AJAX search form
