wagtail/guide

apps/__init__.py, apps/core/factories.py, apps/core/tests/test_locales.py, apps/core/tests/test_page_response.py, apps/frontend/templates/base.html, apps/frontend/templates/components/language_selector.html, apps/guide/settings/base.py, apps/guide/settings/dev.py, apps/guide/urls.py, apps/guide/wsgi.py, apps/monkey_patches.py, manage.py, monkey_patches.py, requirements/development.txt
Monkey patch to accept locales with dots.
=> Add Wagtail locale and simple_translations

apps/core/templates/core/home_page.html, apps/frontend/templates/404.html, apps/frontend/templates/base.html, apps/search/templates/search/search.html
The body class isn't used and is bad practice.
=> Drop body class

apps/core/factories.py, apps/core/management/commands/buildfixtures.py, apps/core/templates/components/header.html, apps/core/templates/core/content_page.html, apps/core/templates/core/home_page.html, apps/frontend/static_src/scss/components/navigation.scss, apps/frontend/static_src/scss/variables.scss
I picked some low hanging fruit to be closer to the latest design iteration.
=> Sync with design

.github/workflows/test.yml, Makefile
Firstly I have edited Makefile's `test` command to only run tests and not linting. Then I have edited `test.yml` to have separate jobs for testing and linting.
=> Split CI setup into separate jobs for tests & linting

apps/core/templates/components/nav_buttons.html, apps/core/templates/core/content_page.html
I merged #41 and forgot to push a commit for this, therefore this PR.
=> move nav buttons to separate template

apps/core/templates/robots.txt, apps/guide/settings/base.py, apps/guide/urls.py, apps/guide/views.py
I have followed [this](https://www.accordbox.com/blog/wagtail-seo-guide/) tutorial to add `robots.txt` and `sitemap.xml` in the project.
=> add robots.txt and sitemap.xml

apps/frontend/static_src/js/main.js, apps/search/views.py
Fixes #50 
Thanks @thibaudcolas . I have fixed the problem. You can review it now.
=> Use `full_url` instead of `url_path` in serializer

apps/core/templates/base.html, poetry.lock, pyproject.toml
Fixes #69, needs #130.
Not using 4.1rc1 yet as I found an issue with wagtail-localize that prevents it from working with 4.1.
=> Upgrade Wagtail to 4.0.4 and Django to 4.1.2

poetry.lock, pyproject.toml
Sorry, I missed another thing...
I've copied the staging env variables to my local machine and tested the setup locally. Hopefully the deployment will go through after this one 🙏
=> Add missing boto3 package for production

cloudflare/caching-worker.js
This adds a Cloudflare caching worker from https://github.com/torchbox/cloudflare-recipes/blob/master/common-caching.js
Note: Deployment is a manual process, requiring the Torchbox sysadmin team.
=> Add Cloudflare worker

apps/guide/settings/base.py
This should improve page load performance for pages with lots of images.
=> Add renditions cache

.stylelintignore, .stylelintrc.json, apps/frontend/static_src/scss/components/alert.scss, apps/frontend/static_src/scss/components/burger.scss, apps/frontend/static_src/scss/components/header.scss, apps/frontend/static_src/scss/components/primary-nav.scss, apps/frontend/static_src/scss/components/rich-text.scss, apps/frontend/static_src/scss/components/section-link.scss, apps/frontend/static_src/scss/components/section.scss, apps/frontend/static_src/scss/components/streamfield.scss, apps/frontend/static_src/scss/components/toc.scss, apps/frontend/static_src/scss/mixins.scss, apps/frontend/static_src/scss/utilities.scss, apps/frontend/static_src/scss/variables.scss, package.json, yarn.lock
* Fixes https://github.com/wagtail/guide/issues/113
* Some files had to be ignored as I was not sure what do to with existing styles, not too critical though.
* Some `important` usage appears to be required so I just ignored a few discrete lines
* Fixed up a few random typos I found in the styles files also, hope that is ok
=> Adoption of Stylelint for SCSS/CSS quality checks

apps/core/templates/components/feedback.html, apps/core/templates/core/blocks/alert.html, apps/frontend/static_src/scss/components/alert.scss
Fixes items in https://github.com/wagtail/guide/issues/150, also aligns icons in alerts centrally (small design fix)
=> Fix heading semantics and icon alignment

CONTRIBUTING.md
Many developers will look to find a contributing page in the repo - this simply tells developers where to look on the guide ore the readme.
- Relates to #68
=> Adds CONTRIBUTING.md - with a link to the guide page

CONTRIBUTORS.md
- Relates to #66 - simply adding a link to the public Guide's about page https://guide.wagtail.org/about/
=> Add CONTRIBUTORS.md file - with a link to the about page

.gitignore, Makefile, README.md
This took me a couple of hours to figure out. 
Might save someone else some time.
=> Adding some information about running the project in Docker

apps/core/templates/base.html, apps/frontend/static_src/js/main.js, apps/guide/urls.py, apps/search/views.py
=> Search only in the active locale

apps/core/templates/404.html
Fixes https://sentry.io/organizations/wagtail-org/issues/3702820405/?project=4504043711037440
=> Fix extends tag in 404.html template

apps/custom_media/image_formats.py, apps/custom_media/tests/test_image_formats.py
=> Override default richtext fullwidth rendition to 900px

apps/core/models/home.py
The introduction was moved to a field but it is missing a FieldPanel for editing
=> Adding a missing fieldpanel

apps/frontend/static_src/scss/components/link-block.scss
=> fixed footer alignment at large viewports

apps/core/templates/base.html
=> Set noindex meta for non-latest pages to prevent indexing

apps/richtext/wagtail_hooks.py
Fixes #201.
Haven't looked into how to test this.
=> Fix `AnchorBlockConverter` for elements with subelements

apps/frontend/static_src/scss/components/footer.scss, apps/frontend/static_src/scss/variables.scss
Fixes  #243
**Before**
**After**
=> set footer to column in mobile view

apps/core/templates/components/nav_buttons.html
=> Fix HTML issues spotted by DebugBear

apps/core/middleware.py, apps/guide/settings/base.py
=> Add middleware to check for published homepage or 404

apps/core/templates/components/feedback.html, apps/core/tests/test_feedback.py, apps/frontend/static_src/js/feedback/index.js, apps/frontend/static_src/scss/components/feedback.scss
resolves #155 and fixes the feedback form heading font color in dark mode.
=> allow to submit text when giving happy feedback

docs/hosting-environment.md
There's no staging environment.
=> Only a production environment exists

Makefile
- This change only compiles our po to mo.
- DRY
https://github.com/wagtail/guide/pull/266/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L55
=> Compile messages by changing dir to apps

apps/frontend/static_src/scss/components/burger.scss, apps/frontend/static_src/scss/components/header.scss
=> Fix menu size
